# Generated by Django 5.2.12 on 2026-03-22 16:56

import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('trigger_type', models.CharField(choices=[('PRE_MATCH', 'Pre-match hype'), ('POST_BET', 'Post-bet reaction'), ('POST_MATCH', 'Post-match reaction'), ('REPLY', 'Reply to comment')], max_length=20, verbose_name='trigger type')),
                ('prompt_used', models.TextField(blank=True, verbose_name='prompt used')),
                ('raw_response', models.TextField(blank=True, verbose_name='raw response')),
                ('filtered', models.BooleanField(default=False, help_text='True if the post-hoc filter rejected this comment.', verbose_name='filtered out')),
                ('error', models.TextField(blank=True, verbose_name='error')),
            ],
            options={
                'verbose_name': 'bot comment',
                'verbose_name_plural': 'bot comments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('persona_prompt', models.TextField(help_text='Full system prompt sent to the LLM. Edit to tweak personality and voice.', verbose_name='persona prompt')),
                ('avatar_icon', models.CharField(default='robot', help_text='Lucide icon name.', max_length=30, verbose_name='avatar icon')),
                ('avatar_bg', models.CharField(default='#374151', help_text='Hex colour for the avatar background.', max_length=10, verbose_name='avatar background')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive bots are skipped by all tasks.', verbose_name='active')),
                ('strategy_type', models.CharField(choices=[('frontrunner', 'Frontrunner'), ('underdog', 'Underdog'), ('parlay', 'Parlay'), ('draw_specialist', 'Draw Specialist'), ('value_hunter', 'Value Hunter'), ('chaos_agent', 'Chaos Agent'), ('all_in_alice', 'All-In Alice'), ('homer', 'Homer (team-loyal)')], max_length=30, verbose_name='strategy type')),
                ('team_tla', models.CharField(blank=True, help_text='Only for homer bots. Must match a Team.tla value.', max_length=5, verbose_name='team TLA')),
            ],
            options={
                'verbose_name': 'bot profile',
                'verbose_name_plural': 'bot profiles',
                'abstract': False,
            },
        ),
    ]
