# Generated by Django 5.2.12 on 2026-03-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epl_bots', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotProfile',
        ),
    ]
