# Generated by Django 5.2.12 on 2026-04-06 14:44

import django.db.models.deletion
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('letter', models.CharField(max_length=1, unique=True, verbose_name='group letter')),
            ],
            options={
                'ordering': ['letter'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('stage_type', models.CharField(choices=[('GROUP', 'Group Stage'), ('ROUND_OF_32', 'Round of 32'), ('ROUND_OF_16', 'Round of 16'), ('QUARTER', 'Quarter-finals'), ('SEMI', 'Semi-finals'), ('THIRD_PLACE', 'Third-place Play-off'), ('FINAL', 'Final')], max_length=15, unique=True, verbose_name='stage type')),
                ('order', models.IntegerField(help_text='Lower = earlier in tournament', verbose_name='display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True, verbose_name='external ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='short name')),
                ('tla', models.CharField(blank=True, max_length=3, verbose_name='TLA')),
                ('crest_url', models.URLField(blank=True, verbose_name='crest URL')),
                ('crest_image', models.ImageField(blank=True, upload_to='worldcup/crests/', verbose_name='crest image')),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-3', max_length=3, verbose_name='country code')),
                ('confederation', models.CharField(blank=True, choices=[('AFC', 'AFC (Asia)'), ('CAF', 'CAF (Africa)'), ('CONCACAF', 'CONCACAF (North/Central America)'), ('CONMEBOL', 'CONMEBOL (South America)'), ('OFC', 'OFC (Oceania)'), ('UEFA', 'UEFA (Europe)')], max_length=10, verbose_name='confederation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True, verbose_name='external ID')),
                ('matchday', models.IntegerField(blank=True, help_text='1-3 for group stage, null for knockouts', null=True, verbose_name='matchday')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='home score')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='away score')),
                ('home_score_et', models.IntegerField(blank=True, null=True, verbose_name='home score (ET)')),
                ('away_score_et', models.IntegerField(blank=True, null=True, verbose_name='away score (ET)')),
                ('home_score_penalties', models.IntegerField(blank=True, null=True, verbose_name='home penalties')),
                ('away_score_penalties', models.IntegerField(blank=True, null=True, verbose_name='away penalties')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('TIMED', 'Timed'), ('IN_PLAY', 'In Play'), ('PAUSED', 'Paused'), ('EXTRA_TIME', 'Extra Time'), ('PENALTY_SHOOTOUT', 'Penalty Shootout'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='status')),
                ('kickoff', models.DateTimeField(verbose_name='kickoff')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='venue')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('season', models.CharField(default='2026', help_text='e.g. 2026', max_length=10, verbose_name='season')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='worldcup_matches.group', verbose_name='group')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='worldcup_matches.stage', verbose_name='stage')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='worldcup_matches.team', verbose_name='away team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='worldcup_matches.team', verbose_name='home team')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='MatchNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('body', models.TextField(blank=True, help_text='Free-form match observations for bot context', verbose_name='notes')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='worldcup_matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name': 'match notes',
                'verbose_name_plural': 'match notes',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='groups', to='worldcup_matches.team'),
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bookmaker', models.CharField(max_length=100, verbose_name='bookmaker')),
                ('home_win', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='home win')),
                ('draw', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='draw')),
                ('away_win', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='away win')),
                ('fetched_at', models.DateTimeField(verbose_name='fetched at')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='worldcup_matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name_plural': 'odds',
                'ordering': ['-fetched_at'],
                'unique_together': {('match', 'bookmaker')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('position', models.IntegerField(verbose_name='position')),
                ('played', models.IntegerField(default=0, verbose_name='played')),
                ('won', models.IntegerField(default=0, verbose_name='won')),
                ('drawn', models.IntegerField(default=0, verbose_name='drawn')),
                ('lost', models.IntegerField(default=0, verbose_name='lost')),
                ('goals_for', models.IntegerField(default=0, verbose_name='goals for')),
                ('goals_against', models.IntegerField(default=0, verbose_name='goals against')),
                ('goal_difference', models.IntegerField(default=0, verbose_name='goal difference')),
                ('points', models.IntegerField(default=0, verbose_name='points')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='worldcup_matches.group', verbose_name='group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='worldcup_matches.team', verbose_name='team')),
            ],
            options={
                'ordering': ['group__letter', 'position'],
                'unique_together': {('group', 'team')},
            },
        ),
    ]
