# Generated by Django 5.2.12 on 2026-04-02 03:12

import django.db.models.deletion
import vinosports.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('league', models.CharField(blank=True, db_index=True, help_text="'epl', 'nba', 'nfl', or blank for cross-league", max_length=3, verbose_name='league')),
                ('article_type', models.CharField(choices=[('recap', 'Game Recap'), ('roundup', 'Weekly Roundup'), ('trend', 'Betting Trend'), ('cross_league', 'Cross-League')], max_length=20, verbose_name='article type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='subtitle')),
                ('body', models.TextField(verbose_name='body')),
                ('hero_emoji', models.CharField(blank=True, help_text='Emoji for article card display', max_length=10, verbose_name='hero emoji')),
                ('game_id_hash', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='game ID hash')),
                ('game_url', models.CharField(blank=True, max_length=200, verbose_name='game URL')),
                ('game_summary', models.CharField(blank=True, help_text='e.g. "Lakers 112 - Celtics 108"', max_length=200, verbose_name='game summary')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('prompt_used', models.TextField(blank=True, verbose_name='prompt used')),
                ('raw_response', models.TextField(blank=True, verbose_name='raw response')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'news article',
                'verbose_name_plural': 'news articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['league', 'status', '-published_at'], name='news_newsar_league_fdb904_idx'), models.Index(fields=['article_type', 'status'], name='news_newsar_article_8ab52f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('article_type', 'recap'), ('game_id_hash__gt', '')), fields=('league', 'game_id_hash'), name='unique_recap_per_game')],
            },
        ),
    ]
