# Generated by Django 5.2.13 on 2026-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article_type',
            field=models.CharField(choices=[('recap', 'Game Recap'), ('roundup', 'Weekly Roundup'), ('trend', 'Betting Trend'), ('cross_league', 'Cross-League'), ('preview', 'League Preview')], max_length=20, verbose_name='article type'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='league',
            field=models.CharField(blank=True, db_index=True, help_text="'epl', 'nba', 'nfl', 'ucl', 'worldcup', or blank for cross-league", max_length=10, verbose_name='league'),
        ),
    ]
