"""Featured Parlays — bot-curated parlay proposals displayed on homepages."""

from decimal import Decimal

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from vinosports.core.models import BaseModel


class FeaturedParlay(BaseModel):
    """A promotional parlay proposal sponsored by a bot (or future: real user).

    These are NOT placed bets — they're previews generated via
    ParlayBuilder.preview() and stored as denormalized snapshots so
    they remain readable after events finish.
    """

    class Status(models.TextChoices):
        ACTIVE = "ACTIVE", _("Active")
        EXPIRED = "EXPIRED", _("Expired")
        CANCELLED = "CANCELLED", _("Cancelled")

    league = models.CharField(
        _("league"),
        max_length=10,
        help_text=_("League identifier, e.g. 'epl' or 'nba'."),
    )
    sponsor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="sponsored_parlays",
        verbose_name=_("sponsor"),
        help_text=_("Bot user who 'sponsors' this featured parlay."),
    )
    title = models.CharField(
        _("title"),
        max_length=120,
        help_text=_("Display title, e.g. 'Weekend Chalk' or 'Underdog Special'."),
    )
    description = models.TextField(
        _("description"),
        blank=True,
        help_text=_("One-liner description generated by Claude."),
    )
    status = models.CharField(
        _("status"),
        max_length=10,
        choices=Status.choices,
        default=Status.ACTIVE,
    )
    expires_at = models.DateTimeField(
        _("expires at"),
        help_text=_("After this time the parlay is no longer shown."),
    )

    # Snapshot of the preview at creation time
    combined_odds = models.DecimalField(
        _("combined odds"),
        max_digits=12,
        decimal_places=2,
        help_text=_("Combined decimal odds at creation."),
    )
    potential_payout = models.DecimalField(
        _("potential payout"),
        max_digits=12,
        decimal_places=2,
        help_text=_("Potential payout at the reference stake."),
    )
    reference_stake = models.DecimalField(
        _("reference stake"),
        max_digits=10,
        decimal_places=2,
        default=Decimal("10.00"),
        help_text=_("Stake used when computing potential_payout."),
    )

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["league", "status"]),
        ]

    def __str__(self):
        return f"{self.title} ({self.league.upper()}) — {self.get_status_display()}"


class FeaturedParlayLeg(BaseModel):
    """A single leg of a featured parlay — fully denormalized for display."""

    featured_parlay = models.ForeignKey(
        FeaturedParlay,
        on_delete=models.CASCADE,
        related_name="legs",
        verbose_name=_("featured parlay"),
    )
    event_id = models.IntegerField(
        _("event ID"),
        help_text=_("PK of the match/game (not a FK to keep this in core)."),
    )
    event_label = models.CharField(
        _("event label"),
        max_length=200,
        help_text=_("e.g. 'Arsenal vs Chelsea' — denormalized for display."),
    )
    selection = models.CharField(
        _("selection"),
        max_length=20,
        help_text=_("Raw selection value, e.g. 'HOME_WIN', 'OVER'."),
    )
    selection_label = models.CharField(
        _("selection label"),
        max_length=60,
        help_text=_("Human-readable selection, e.g. 'Home Win', 'Over 222.5'."),
    )
    odds_snapshot = models.DecimalField(
        _("odds snapshot"),
        max_digits=10,
        decimal_places=2,
        help_text=_("Decimal odds at the time of creation."),
    )
    extras_json = models.JSONField(
        _("extras"),
        default=dict,
        blank=True,
        help_text=_('League-specific data, e.g. {"market": "SPREAD", "line": -3.5}.'),
    )

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.event_label} — {self.selection_label} @ {self.odds_snapshot}"
