# Generated by Django 5.2.12 on 2026-03-28 19:30

import django.db.models.deletion
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('HALFTIME', 'Halftime'), ('FINAL', 'Final'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('game_date', models.DateField()),
                ('tip_off', models.DateTimeField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('arena', models.CharField(blank=True, max_length=200)),
                ('postseason', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-game_date', '-tip_off'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
                ('logo_url', models.URLField(blank=True)),
                ('conference', models.CharField(choices=[('EAST', 'Eastern'), ('WEST', 'Western')], max_length=4)),
                ('division', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('h2h', models.JSONField(blank=True, default=dict)),
                ('form', models.JSONField(blank=True, default=dict)),
                ('injuries', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='nba_games.game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jersey_number', models.CharField(blank=True, max_length=20)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('draft_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draft_round', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draft_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('headshot_url', models.URLField(blank=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='nba_games.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='nba_games.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='nba_games.team'),
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bookmaker', models.CharField(max_length=100, verbose_name='bookmaker')),
                ('home_moneyline', models.IntegerField(blank=True, null=True, verbose_name='home moneyline')),
                ('away_moneyline', models.IntegerField(blank=True, null=True, verbose_name='away moneyline')),
                ('spread_line', models.FloatField(blank=True, null=True, verbose_name='spread line')),
                ('spread_home', models.IntegerField(blank=True, null=True, verbose_name='spread home odds')),
                ('spread_away', models.IntegerField(blank=True, null=True, verbose_name='spread away odds')),
                ('total_line', models.FloatField(blank=True, null=True, verbose_name='total line')),
                ('over_odds', models.IntegerField(blank=True, null=True, verbose_name='over odds')),
                ('under_odds', models.IntegerField(blank=True, null=True, verbose_name='under odds')),
                ('fetched_at', models.DateTimeField(verbose_name='fetched at')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='nba_games.game', verbose_name='game')),
            ],
            options={
                'verbose_name_plural': 'odds',
                'ordering': ['-fetched_at'],
                'unique_together': {('game', 'bookmaker')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('season', models.IntegerField()),
                ('conference', models.CharField(choices=[('EAST', 'Eastern'), ('WEST', 'Western')], max_length=4)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('win_pct', models.FloatField(default=0.0)),
                ('games_behind', models.FloatField(default=0.0)),
                ('streak', models.CharField(blank=True, max_length=10)),
                ('home_record', models.CharField(blank=True, max_length=10)),
                ('away_record', models.CharField(blank=True, max_length=10)),
                ('conference_rank', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='nba_games.team')),
            ],
            options={
                'ordering': ['conference', 'conference_rank'],
                'unique_together': {('team', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PlayerBoxScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('player_external_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=100)),
                ('player_position', models.CharField(blank=True, max_length=10)),
                ('minutes', models.CharField(blank=True, max_length=10)),
                ('points', models.SmallIntegerField(default=0)),
                ('fgm', models.SmallIntegerField(default=0)),
                ('fga', models.SmallIntegerField(default=0)),
                ('fg3m', models.SmallIntegerField(default=0)),
                ('fg3a', models.SmallIntegerField(default=0)),
                ('ftm', models.SmallIntegerField(default=0)),
                ('fta', models.SmallIntegerField(default=0)),
                ('oreb', models.SmallIntegerField(default=0)),
                ('dreb', models.SmallIntegerField(default=0)),
                ('reb', models.SmallIntegerField(default=0)),
                ('ast', models.SmallIntegerField(default=0)),
                ('stl', models.SmallIntegerField(default=0)),
                ('blk', models.SmallIntegerField(default=0)),
                ('turnovers', models.SmallIntegerField(default=0)),
                ('pf', models.SmallIntegerField(default=0)),
                ('plus_minus', models.SmallIntegerField(default=0)),
                ('starter', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='nba_games.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_scores', to='nba_games.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='nba_games.team')),
            ],
            options={
                'ordering': ['-starter', '-points'],
                'unique_together': {('game', 'player_external_id')},
            },
        ),
    ]
