# Generated by Django 5.2.12 on 2026-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, upload_to='nba/logos/'),
        ),
    ]
