# Generated by Django 5.2.12 on 2026-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0002_add_player_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
