# Generated by Django 5.2.12 on 2026-04-02 02:05

import django.db.models.deletion
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0002_add_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('body', models.TextField(blank=True, help_text='Free-form game observations for bot context', verbose_name='notes')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='nba_games.game', verbose_name='game')),
            ],
            options={
                'verbose_name': 'game notes',
                'verbose_name_plural': 'game notes',
            },
        ),
    ]
