# Generated by Django 5.2.12 on 2026-03-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epl_matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='crest_image',
            field=models.ImageField(blank=True, upload_to='epl/crests/', verbose_name='crest image'),
        ),
    ]
