# Generated by Django 5.2.13 on 2026-04-09 18:15

import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubredditSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('league', models.CharField(db_index=True, max_length=20)),
                ('subreddit', models.CharField(max_length=100)),
                ('fetched_at', models.DateTimeField()),
                ('data', models.JSONField(help_text="Structured post + comment data from the subreddit's hot feed")),
            ],
            options={
                'verbose_name': 'Subreddit Snapshot',
                'verbose_name_plural': 'Subreddit Snapshots',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
