# Generated by Django 5.2.12 on 2026-03-25 23:47

import django.db.models.deletion
import vinosports.core.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epl_matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='payout')),
                ('selection', models.CharField(choices=[('HOME_WIN', 'Home Win'), ('DRAW', 'Draw'), ('AWAY_WIN', 'Away Win')], max_length=10, verbose_name='selection')),
                ('odds_at_placement', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='odds at placement')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='epl_matches.match', verbose_name='match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_bets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parlay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='payout')),
                ('max_payout', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12, verbose_name='max payout')),
                ('combined_odds', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='combined odds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_parlays', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParlayLeg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('selection', models.CharField(choices=[('HOME_WIN', 'Home Win'), ('DRAW', 'Draw'), ('AWAY_WIN', 'Away Win')], max_length=10, verbose_name='selection')),
                ('odds_at_placement', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='odds at placement')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlay_legs', to='epl_matches.match', verbose_name='match')),
                ('parlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='epl_betting.parlay', verbose_name='parlay')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('parlay', 'match')},
            },
        ),
    ]
