# Generated by Django 5.2.12 on 2026-03-28 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_featured_parlay'),
        ('epl_betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlay',
            name='featured_parlay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_placed_parlays', to='betting.featuredparlay', verbose_name='featured parlay'),
        ),
    ]
