# Generated by Django 5.2.12 on 2026-03-30 01:20

import django.db.models.deletion
import vinosports.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epl_betting', '0002_initial'),
        ('epl_matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesMarket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('season', models.CharField(max_length=10, verbose_name='season')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SUSPENDED', 'Suspended'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10, verbose_name='status')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='settled at')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('market_type', models.CharField(choices=[('WINNER', 'League Winner'), ('TOP_4', 'Top 4 Finish'), ('RELEGATION', 'Relegation')], max_length=12, verbose_name='market type')),
            ],
            options={
                'verbose_name': 'futures market',
                'verbose_name_plural': 'futures markets',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('season', 'market_type')},
            },
        ),
        migrations.CreateModel(
            name='FuturesOutcome',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_winner', models.BooleanField(default=False, verbose_name='is winner')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate if team is eliminated', verbose_name='is active')),
                ('odds', models.DecimalField(decimal_places=2, help_text='Decimal odds (e.g., 2.50)', max_digits=8, verbose_name='odds')),
                ('odds_updated_at', models.DateTimeField(auto_now=True, verbose_name='odds updated at')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='epl_betting.futuresmarket', verbose_name='market')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures_outcomes', to='epl_matches.team', verbose_name='team')),
            ],
            options={
                'ordering': ['odds'],
                'abstract': False,
                'unique_together': {('market', 'team')},
            },
        ),
        migrations.CreateModel(
            name='FuturesBet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='payout')),
                ('odds_at_placement', models.DecimalField(decimal_places=2, help_text='Decimal odds locked at bet placement', max_digits=8, verbose_name='odds at placement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_futures_bets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='epl_betting.futuresoutcome', verbose_name='outcome')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
