# Generated by Django 5.2.12 on 2026-03-22 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epl_betting', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_bets', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='parlay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_parlays', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='parlayleg',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlay_legs', to='matches.match', verbose_name='match'),
        ),
        migrations.AddField(
            model_name='parlayleg',
            name='parlay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='epl_betting.parlay', verbose_name='parlay'),
        ),
        migrations.AlterUniqueTogether(
            name='parlayleg',
            unique_together={('parlay', 'match')},
        ),
    ]
