# Generated by Django 5.2.12 on 2026-03-22 16:56

import vinosports.core.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('icon', models.CharField(help_text='Phosphor icon name', max_length=50, verbose_name='icon')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic')], default='common', max_length=10, verbose_name='rarity')),
            ],
            options={
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bailout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance after')),
                ('transaction_type', models.CharField(choices=[('SIGNUP', 'Signup bonus'), ('BET_PLACEMENT', 'Bet placed'), ('BET_WIN', 'Bet won'), ('BET_VOID', 'Bet voided'), ('PARLAY_PLACEMENT', 'Parlay placed'), ('PARLAY_WIN', 'Parlay won'), ('PARLAY_VOID', 'Parlay voided'), ('CHALLENGE_REWARD', 'Challenge reward'), ('REWARD', 'Reward'), ('BAILOUT', 'Bailout'), ('ADMIN_RESET', 'Admin reset')], max_length=20, verbose_name='type')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='description')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bankruptcy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('balance_at_bankruptcy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance at bankruptcy')),
            ],
            options={
                'verbose_name_plural': 'bankruptcies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='earned at')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='balance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('total_bets', models.PositiveIntegerField(default=0, verbose_name='total bets')),
                ('total_wins', models.PositiveIntegerField(default=0, verbose_name='total wins')),
                ('total_losses', models.PositiveIntegerField(default=0, verbose_name='total losses')),
                ('total_staked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total staked')),
                ('total_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total payout')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='net profit')),
                ('current_streak', models.IntegerField(default=0, help_text='Positive = win streak, negative = loss streak', verbose_name='current streak')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='best win streak')),
            ],
            options={
                'verbose_name_plural': 'user stats',
            },
        ),
    ]
