# Generated by Django 5.2.12 on 2026-03-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bailout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bailouts', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='bankruptcy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankruptcies', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='bailout',
            name='bankruptcy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bailout', to='betting.bankruptcy', verbose_name='bankruptcy'),
        ),
        migrations.AddField(
            model_name='featuredparlay',
            name='sponsor',
            field=models.ForeignKey(help_text="Bot user who 'sponsors' this featured parlay.", on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_parlays', to=settings.AUTH_USER_MODEL, verbose_name='sponsor'),
        ),
        migrations.AddField(
            model_name='featuredparlayleg',
            name='featured_parlay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='betting.featuredparlay', verbose_name='featured parlay'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='betting.badge', verbose_name='badge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['user', 'created_at'], name='betting_bal_user_id_2cdeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredparlay',
            index=models.Index(fields=['league', 'status'], name='betting_fea_league_fbaf4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
