# Generated by Django 5.2.12 on 2026-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SIGNUP', 'Signup bonus'), ('BET_PLACEMENT', 'Bet placed'), ('BET_WIN', 'Bet won'), ('BET_VOID', 'Bet voided'), ('PARLAY_PLACEMENT', 'Parlay placed'), ('PARLAY_WIN', 'Parlay won'), ('PARLAY_VOID', 'Parlay voided'), ('CHALLENGE_REWARD', 'Challenge reward'), ('REWARD', 'Reward'), ('BAILOUT', 'Bailout'), ('PROMO_CODE', 'Promo code bonus'), ('ADMIN_RESET', 'Admin reset')], max_length=20, verbose_name='type'),
        ),
    ]
