# Generated by Django 5.2.12 on 2026-03-26 19:17

import django.db.models.deletion
import vinosports.core.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_alter_balancetransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedParlay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('league', models.CharField(help_text="League identifier, e.g. 'epl' or 'nba'.", max_length=10, verbose_name='league')),
                ('title', models.CharField(help_text="Display title, e.g. 'Weekend Chalk' or 'Underdog Special'.", max_length=120, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='One-liner description generated by Claude.', verbose_name='description')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('expires_at', models.DateTimeField(help_text='After this time the parlay is no longer shown.', verbose_name='expires at')),
                ('combined_odds', models.DecimalField(decimal_places=2, help_text='Combined decimal odds at creation.', max_digits=12, verbose_name='combined odds')),
                ('potential_payout', models.DecimalField(decimal_places=2, help_text='Potential payout at the reference stake.', max_digits=12, verbose_name='potential payout')),
                ('reference_stake', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Stake used when computing potential_payout.', max_digits=10, verbose_name='reference stake')),
                ('sponsor', models.ForeignKey(help_text="Bot user who 'sponsors' this featured parlay.", on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_parlays', to=settings.AUTH_USER_MODEL, verbose_name='sponsor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedParlayLeg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_id', models.IntegerField(help_text='PK of the match/game (not a FK to keep this in core).', verbose_name='event ID')),
                ('event_label', models.CharField(help_text="e.g. 'Arsenal vs Chelsea' — denormalized for display.", max_length=200, verbose_name='event label')),
                ('selection', models.CharField(help_text="Raw selection value, e.g. 'HOME_WIN', 'OVER'.", max_length=20, verbose_name='selection')),
                ('selection_label', models.CharField(help_text="Human-readable selection, e.g. 'Home Win', 'Over 222.5'.", max_length=60, verbose_name='selection label')),
                ('odds_snapshot', models.DecimalField(decimal_places=2, help_text='Decimal odds at the time of creation.', max_digits=10, verbose_name='odds snapshot')),
                ('extras_json', models.JSONField(blank=True, default=dict, help_text='League-specific data, e.g. {"market": "SPREAD", "line": -3.5}.', verbose_name='extras')),
                ('featured_parlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='betting.featuredparlay', verbose_name='featured parlay')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='featuredparlay',
            index=models.Index(fields=['league', 'status'], name='betting_fea_league_fbaf4c_idx'),
        ),
    ]
