# Generated by Django 5.2.12 on 2026-04-02 17:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_alter_balancetransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='balance after'),
        ),
        migrations.AlterField(
            model_name='bankruptcy',
            name='balance_at_bankruptcy',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='balance at bankruptcy'),
        ),
        migrations.AlterField(
            model_name='featuredparlay',
            name='reference_stake',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Stake used when computing potential_payout.', max_digits=10, verbose_name='reference stake'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=14, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='net profit'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total payout'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_staked',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total staked'),
        ),
    ]
