# Generated by Django 5.2.12 on 2026-04-02

from decimal import Decimal
from django.db import migrations, models


def update_existing_featured_parlays(apps, schema_editor):
    """Update existing featured parlays to use $10,000 stake and recalculate payouts."""
    FeaturedParlay = apps.get_model("betting", "FeaturedParlay")
    new_stake = Decimal("10000.00")
    for fp in FeaturedParlay.objects.filter(
        reference_stake__in=[Decimal("10.00"), Decimal("1000.00")]
    ):
        fp.reference_stake = new_stake
        fp.potential_payout = (fp.combined_odds * new_stake).quantize(Decimal("0.01"))
        fp.save(update_fields=["reference_stake", "potential_payout"])


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0004_alter_bailout_amount_alter_balancetransaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredparlay",
            name="reference_stake",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10000.00"),
                help_text="Stake used when computing potential_payout.",
                max_digits=10,
                verbose_name="reference stake",
            ),
        ),
        migrations.RunPython(
            update_existing_featured_parlays,
            migrations.RunPython.noop,
        ),
    ]
