# Generated by Django 5.2.12 on 2026-03-30 23:51

import django.db.models.deletion
import vinosports.core.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0003_alter_balancetransaction_transaction_type'),
        ('nfl_games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='payout')),
                ('market', models.CharField(choices=[('MONEYLINE', 'Moneyline'), ('SPREAD', 'Spread'), ('TOTAL', 'Total')], max_length=10, verbose_name='market')),
                ('selection', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away'), ('OVER', 'Over'), ('UNDER', 'Under')], max_length=10, verbose_name='selection')),
                ('odds_at_placement', models.IntegerField(help_text='American odds (e.g., -110, +150)', verbose_name='odds at placement')),
                ('line', models.FloatField(blank=True, help_text='Spread or total line (e.g., -3.5 or 44.5)', null=True, verbose_name='line')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='nfl_games.game', verbose_name='game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_bets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuturesMarket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('season', models.CharField(max_length=10, verbose_name='season')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SUSPENDED', 'Suspended'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10, verbose_name='status')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='settled at')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('market_type', models.CharField(choices=[('SUPER_BOWL', 'Super Bowl Winner'), ('AFC_CHAMPION', 'AFC Champion'), ('NFC_CHAMPION', 'NFC Champion'), ('DIVISION', 'Division Winner')], max_length=15, verbose_name='market type')),
                ('division', models.CharField(blank=True, choices=[('AFC_EAST', 'AFC East'), ('AFC_NORTH', 'AFC North'), ('AFC_SOUTH', 'AFC South'), ('AFC_WEST', 'AFC West'), ('NFC_EAST', 'NFC East'), ('NFC_NORTH', 'NFC North'), ('NFC_SOUTH', 'NFC South'), ('NFC_WEST', 'NFC West')], default='', help_text='Only for DIVISION market type', max_length=10, verbose_name='division')),
            ],
            options={
                'verbose_name': 'futures market',
                'verbose_name_plural': 'futures markets',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('season', 'market_type', 'division')},
            },
        ),
        migrations.CreateModel(
            name='FuturesOutcome',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_winner', models.BooleanField(default=False, verbose_name='is winner')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate if team is eliminated', verbose_name='is active')),
                ('odds', models.IntegerField(help_text='American odds (e.g., +350, -150)', verbose_name='odds')),
                ('odds_updated_at', models.DateTimeField(auto_now=True, verbose_name='odds updated at')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='nfl_betting.futuresmarket', verbose_name='market')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures_outcomes', to='nfl_games.team', verbose_name='team')),
            ],
            options={
                'ordering': ['odds'],
                'abstract': False,
                'unique_together': {('market', 'team')},
            },
        ),
        migrations.CreateModel(
            name='FuturesBet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='payout')),
                ('odds_at_placement', models.IntegerField(help_text='American odds locked at bet placement', verbose_name='odds at placement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_futures_bets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='nfl_betting.futuresoutcome', verbose_name='outcome')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parlay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='payout')),
                ('max_payout', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12, verbose_name='max payout')),
                ('combined_odds', models.IntegerField(help_text='Combined American odds', verbose_name='combined odds')),
                ('featured_parlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_placed_parlays', to='betting.featuredparlay', verbose_name='featured parlay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_parlays', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bookmaker', models.CharField(max_length=100, verbose_name='bookmaker')),
                ('home_moneyline', models.IntegerField(blank=True, null=True, verbose_name='home moneyline')),
                ('away_moneyline', models.IntegerField(blank=True, null=True, verbose_name='away moneyline')),
                ('spread_line', models.FloatField(blank=True, null=True, verbose_name='spread line')),
                ('spread_home', models.IntegerField(blank=True, null=True, verbose_name='spread home odds')),
                ('spread_away', models.IntegerField(blank=True, null=True, verbose_name='spread away odds')),
                ('total_line', models.FloatField(blank=True, null=True, verbose_name='total line')),
                ('over_odds', models.IntegerField(blank=True, null=True, verbose_name='over odds')),
                ('under_odds', models.IntegerField(blank=True, null=True, verbose_name='under odds')),
                ('fetched_at', models.DateTimeField(verbose_name='fetched at')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='nfl_games.game', verbose_name='game')),
            ],
            options={
                'verbose_name_plural': 'odds',
                'ordering': ['-fetched_at'],
                'unique_together': {('game', 'bookmaker')},
            },
        ),
        migrations.CreateModel(
            name='ParlayLeg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('market', models.CharField(choices=[('MONEYLINE', 'Moneyline'), ('SPREAD', 'Spread'), ('TOTAL', 'Total')], max_length=10, verbose_name='market')),
                ('selection', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away'), ('OVER', 'Over'), ('UNDER', 'Under')], max_length=10, verbose_name='selection')),
                ('odds_at_placement', models.IntegerField(verbose_name='odds at placement')),
                ('line', models.FloatField(blank=True, null=True, verbose_name='line')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlay_legs', to='nfl_games.game', verbose_name='game')),
                ('parlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='nfl_betting.parlay', verbose_name='parlay')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('parlay', 'game')},
            },
        ),
    ]
