# Generated by Django 5.2.12 on 2026-04-02 17:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_betting', '0001_betting_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='payout'),
        ),
        migrations.AlterField(
            model_name='betslip',
            name='stake',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='stake'),
        ),
        migrations.AlterField(
            model_name='futuresbet',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='payout'),
        ),
        migrations.AlterField(
            model_name='futuresbet',
            name='stake',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='stake'),
        ),
        migrations.AlterField(
            model_name='parlay',
            name='max_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000000.00'), max_digits=14, verbose_name='max payout'),
        ),
        migrations.AlterField(
            model_name='parlay',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='payout'),
        ),
        migrations.AlterField(
            model_name='parlay',
            name='stake',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='stake'),
        ),
    ]
