# Generated by Django 5.2.12 on 2026-04-02 21:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_betting', '0002_alter_betslip_payout_alter_betslip_stake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlay',
            name='max_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000000000.00'), max_digits=14, verbose_name='max payout'),
        ),
    ]
