# Generated by Django 5.2.12 on 2026-03-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rewards', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='rewarddistribution',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='rewards.reward', verbose_name='reward'),
        ),
        migrations.AddField(
            model_name='rewarddistribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_distributions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='rewardrule',
            name='reward',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='rewards.reward', verbose_name='reward'),
        ),
        migrations.AlterUniqueTogether(
            name='rewarddistribution',
            unique_together={('reward', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='rewardrule',
            unique_together={('rule_type', 'threshold')},
        ),
    ]
