# Generated by Django 5.2.12 on 2026-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=280, verbose_name='message')),
                ('url', models.CharField(blank=True, default='', max_length=200, verbose_name='url')),
                ('icon', models.CharField(default='lightning', max_length=50, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('broadcast_at', models.DateTimeField(blank=True, null=True, verbose_name='broadcast at')),
                ('event_type', models.CharField(choices=[('bot_bet', 'Bot Bet'), ('bot_comment', 'Bot Comment'), ('score_change', 'Score Change'), ('odds_update', 'Odds Update'), ('bet_settlement', 'Bet Settlement')], max_length=20)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['broadcast_at', 'created_at'], name='epl_act_pending_bcast_idx')],
            },
        ),
    ]
