# Generated by Django 5.2.12 on 2026-03-28 19:30

import django.db.models.deletion
import vinosports.core.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nba_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parlay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='payout')),
                ('max_payout', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12, verbose_name='max payout')),
                ('combined_odds', models.IntegerField(help_text='Combined American odds', verbose_name='combined odds')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParlayLeg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('market', models.CharField(choices=[('MONEYLINE', 'Moneyline'), ('SPREAD', 'Spread'), ('TOTAL', 'Total')], max_length=10, verbose_name='market')),
                ('selection', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away'), ('OVER', 'Over'), ('UNDER', 'Under')], max_length=10, verbose_name='selection')),
                ('odds_at_placement', models.IntegerField(verbose_name='odds at placement')),
                ('line', models.FloatField(blank=True, null=True, verbose_name='line')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='payout')),
                ('market', models.CharField(choices=[('MONEYLINE', 'Moneyline'), ('SPREAD', 'Spread'), ('TOTAL', 'Total')], max_length=10, verbose_name='market')),
                ('selection', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away'), ('OVER', 'Over'), ('UNDER', 'Under')], max_length=10, verbose_name='selection')),
                ('odds_at_placement', models.IntegerField(help_text='American odds (e.g., -110, +150)', verbose_name='odds at placement')),
                ('line', models.FloatField(blank=True, help_text='Spread or total line (e.g., -3.5 or 224.5)', null=True, verbose_name='line')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='nba_games.game', verbose_name='game')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
