# Generated by Django 5.2.12 on 2026-03-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0002_initial'),
        ('nba_betting', '0001_initial'),
        ('nba_games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_bets', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='parlay',
            name='featured_parlay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_placed_parlays', to='betting.featuredparlay', verbose_name='featured parlay'),
        ),
        migrations.AddField(
            model_name='parlay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_parlays', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='parlayleg',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlay_legs', to='nba_games.game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='parlayleg',
            name='parlay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='nba_betting.parlay', verbose_name='parlay'),
        ),
        migrations.AlterUniqueTogether(
            name='parlayleg',
            unique_together={('parlay', 'game')},
        ),
    ]
