# Generated by Django 5.2.12 on 2026-03-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='max_daily_bets',
            field=models.PositiveIntegerField(default=5, help_text='Maximum bets this bot can place per day.', verbose_name='max daily bets'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='risk_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier applied to base stake percentage.', verbose_name='risk multiplier'),
        ),
        migrations.AlterField(
            model_name='botprofile',
            name='strategy_type',
            field=models.CharField(choices=[('frontrunner', 'Frontrunner'), ('underdog', 'Underdog'), ('spread_shark', 'Spread Shark'), ('parlay', 'Parlay'), ('total_guru', 'Total Guru'), ('chaos_agent', 'Chaos Agent'), ('all_in_alice', 'All-In Alice'), ('homer', 'Homer (team-loyal)'), ('anti_homer', 'Anti-Homer (revenge)')], max_length=30, verbose_name='strategy type'),
        ),
    ]
