# Generated by Django 5.2.12 on 2026-03-24 00:16

import django.db.models.deletion
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_bots', '0002_botprofile_max_daily_bets_botprofile_risk_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('windows', models.JSONField(help_text='JSON list of activity windows defining schedule and probabilities.', verbose_name='activity windows')),
                ('active_from', models.DateField(blank=True, help_text='Optional start date. Template is inactive before this date.', null=True, verbose_name='active from')),
                ('active_to', models.DateField(blank=True, help_text='Optional end date. Template is inactive after this date.', null=True, verbose_name='active to')),
            ],
            options={
                'verbose_name': 'schedule template',
                'verbose_name_plural': 'schedule templates',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='botprofile',
            name='schedule_template',
            field=models.ForeignKey(blank=True, help_text='Activity schedule. Bots without a template are always eligible.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='nba_bots.scheduletemplate', verbose_name='schedule template'),
        ),
    ]
