# Generated by Django 5.2.12 on 2026-03-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_bots', '0003_schedule_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botprofile',
            name='favorite_team',
        ),
        migrations.RemoveField(
            model_name='botprofile',
            name='schedule_template',
        ),
        migrations.RemoveField(
            model_name='botprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScheduleTemplate',
        ),
        migrations.DeleteModel(
            name='BotProfile',
        ),
    ]
