# Generated by Django 5.2.12 on 2026-03-22 16:56

import django.db.models.deletion
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('icon', models.CharField(help_text='Phosphor icon name', max_length=50)),
                ('challenge_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('SPECIAL', 'Special Event')], max_length=10)),
                ('criteria_type', models.CharField(choices=[('BET_COUNT', 'Place N bets'), ('BET_ON_UNDERDOG', 'Bet on underdog'), ('WIN_COUNT', 'Win N bets'), ('WIN_STREAK', 'Win N in a row'), ('PARLAY_PLACED', 'Place a parlay'), ('PARLAY_WON', 'Win a parlay'), ('TOTAL_STAKED', 'Stake N+ credits'), ('BET_ALL_MATCHES', 'Bet on every match'), ('CORRECT_PREDICTIONS', 'Predict N+ correct')], max_length=25)),
                ('criteria_params', models.JSONField(default=dict, help_text='e.g. {"target": 3, "odds_min": "3.00"}')),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(blank=True, help_text='Optional badge awarded on completion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.badge')),
            ],
            options={
                'ordering': ['challenge_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='UPCOMING', max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('matchday', models.IntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='challenges.challengetemplate')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('progress', models.IntegerField(default=0)),
                ('target', models.IntegerField(help_text='Denormalized from challenge criteria for display')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_credited', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to='challenges.challenge')),
            ],
            options={
                'ordering': ['-challenge__starts_at'],
            },
        ),
    ]
