# Generated by Django 5.2.12 on 2026-03-30 23:32

import django.db.models.deletion
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('HALFTIME', 'Halftime'), ('FINAL', 'Final'), ('FINAL_OT', 'Final (OT)'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('game_date', models.DateField()),
                ('kickoff', models.DateTimeField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('week', models.IntegerField(blank=True, null=True)),
                ('postseason', models.BooleanField(default=False)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('home_q1', models.SmallIntegerField(blank=True, null=True)),
                ('home_q2', models.SmallIntegerField(blank=True, null=True)),
                ('home_q3', models.SmallIntegerField(blank=True, null=True)),
                ('home_q4', models.SmallIntegerField(blank=True, null=True)),
                ('home_ot', models.SmallIntegerField(blank=True, null=True)),
                ('away_q1', models.SmallIntegerField(blank=True, null=True)),
                ('away_q2', models.SmallIntegerField(blank=True, null=True)),
                ('away_q3', models.SmallIntegerField(blank=True, null=True)),
                ('away_q4', models.SmallIntegerField(blank=True, null=True)),
                ('away_ot', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-game_date', '-kickoff'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('conference', models.CharField(choices=[('AFC', 'AFC'), ('NFC', 'NFC')], max_length=3)),
                ('division', models.CharField(choices=[('AFC_EAST', 'AFC East'), ('AFC_NORTH', 'AFC North'), ('AFC_SOUTH', 'AFC South'), ('AFC_WEST', 'AFC West'), ('NFC_EAST', 'NFC East'), ('NFC_NORTH', 'NFC North'), ('NFC_SOUTH', 'NFC South'), ('NFC_WEST', 'NFC West')], max_length=10)),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('h2h', models.JSONField(blank=True, default=dict)),
                ('form', models.JSONField(blank=True, default=dict)),
                ('injuries', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='nfl_games.game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=30)),
                ('position_abbreviation', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jersey_number', models.CharField(blank=True, max_length=20)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='nfl_games.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='nfl_games.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='nfl_games.team'),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('season', models.IntegerField()),
                ('conference', models.CharField(choices=[('AFC', 'AFC'), ('NFC', 'NFC')], max_length=3)),
                ('division', models.CharField(choices=[('AFC_EAST', 'AFC East'), ('AFC_NORTH', 'AFC North'), ('AFC_SOUTH', 'AFC South'), ('AFC_WEST', 'AFC West'), ('NFC_EAST', 'NFC East'), ('NFC_NORTH', 'NFC North'), ('NFC_SOUTH', 'NFC South'), ('NFC_WEST', 'NFC West')], max_length=10)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('win_pct', models.FloatField(default=0.0)),
                ('division_wins', models.IntegerField(default=0)),
                ('division_losses', models.IntegerField(default=0)),
                ('conference_wins', models.IntegerField(default=0)),
                ('conference_losses', models.IntegerField(default=0)),
                ('points_for', models.IntegerField(default=0)),
                ('points_against', models.IntegerField(default=0)),
                ('streak', models.CharField(blank=True, max_length=10)),
                ('division_rank', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='nfl_games.team')),
            ],
            options={
                'ordering': ['division', 'division_rank'],
                'unique_together': {('team', 'season')},
            },
        ),
    ]
