# Generated by Django 5.2.12 on 2026-03-25 06:15

import django.db.models.deletion
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBoxScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('player_external_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=100)),
                ('player_position', models.CharField(blank=True, max_length=10)),
                ('minutes', models.CharField(blank=True, max_length=10)),
                ('points', models.SmallIntegerField(default=0)),
                ('fgm', models.SmallIntegerField(default=0)),
                ('fga', models.SmallIntegerField(default=0)),
                ('fg3m', models.SmallIntegerField(default=0)),
                ('fg3a', models.SmallIntegerField(default=0)),
                ('ftm', models.SmallIntegerField(default=0)),
                ('fta', models.SmallIntegerField(default=0)),
                ('oreb', models.SmallIntegerField(default=0)),
                ('dreb', models.SmallIntegerField(default=0)),
                ('reb', models.SmallIntegerField(default=0)),
                ('ast', models.SmallIntegerField(default=0)),
                ('stl', models.SmallIntegerField(default=0)),
                ('blk', models.SmallIntegerField(default=0)),
                ('turnovers', models.SmallIntegerField(default=0)),
                ('pf', models.SmallIntegerField(default=0)),
                ('plus_minus', models.SmallIntegerField(default=0)),
                ('starter', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='games.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='games.team')),
            ],
            options={
                'ordering': ['-starter', '-points'],
                'unique_together': {('game', 'player_external_id')},
            },
        ),
    ]
