# Generated by Django 5.2.12 on 2026-03-31 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nfl_bots', '0001_initial_models'),
        ('nfl_discussions', '0001_initial_models'),
        ('nfl_games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botcomment',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_comment_meta', to='nfl_discussions.comment', verbose_name='posted comment'),
        ),
        migrations.AddField(
            model_name='botcomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_comments', to='nfl_games.game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='botcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_replies', to='nfl_discussions.comment', verbose_name='replied to'),
        ),
        migrations.AddField(
            model_name='botcomment',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_bot': True}, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_bot_comments', to=settings.AUTH_USER_MODEL, verbose_name='bot user'),
        ),
        migrations.AddIndex(
            model_name='botcomment',
            index=models.Index(fields=['game', 'trigger_type'], name='nfl_bots_bo_game_id_9a398a_idx'),
        ),
        migrations.AddConstraint(
            model_name='botcomment',
            constraint=models.UniqueConstraint(fields=('user', 'game', 'trigger_type'), name='unique_nfl_bot_comment_per_trigger'),
        ),
    ]
