# Generated by Django 5.2.12 on 2026-03-28 19:30

import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('persona_prompt', models.TextField(help_text='Personality-only system prompt sent to the LLM. Do NOT include team references — team context is injected at runtime.', verbose_name='persona prompt')),
                ('avatar_icon', models.CharField(default='robot', help_text='Lucide icon name.', max_length=30, verbose_name='avatar icon')),
                ('avatar_bg', models.CharField(default='#374151', help_text='Hex colour for the avatar background.', max_length=10, verbose_name='avatar background')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive bots are skipped by all tasks.', verbose_name='active')),
                ('strategy_type', models.CharField(choices=[('frontrunner', 'Frontrunner'), ('underdog', 'Underdog'), ('spread_shark', 'Spread Shark'), ('parlay', 'Parlay'), ('total_guru', 'Total Guru'), ('draw_specialist', 'Draw Specialist'), ('value_hunter', 'Value Hunter'), ('chaos_agent', 'Chaos Agent'), ('all_in_alice', 'All-In Alice'), ('homer', 'Homer'), ('anti_homer', 'Anti-Homer')], max_length=30, verbose_name='strategy type')),
                ('risk_multiplier', models.FloatField(default=1.0, help_text='Multiplier applied to base stake percentage.', verbose_name='risk multiplier')),
                ('max_daily_bets', models.PositiveIntegerField(default=5, help_text='Maximum bets this bot can place per day across all leagues.', verbose_name='max daily bets')),
                ('active_in_epl', models.BooleanField(default=True, verbose_name='active in EPL')),
                ('active_in_nba', models.BooleanField(default=True, verbose_name='active in NBA')),
                ('active_in_nfl', models.BooleanField(default=False, verbose_name='active in NFL')),
                ('epl_team_tla', models.CharField(blank=True, help_text='Three-letter abbreviation of favourite EPL team (e.g. CHE, ARS).', max_length=5, verbose_name='EPL team TLA')),
                ('nba_team_abbr', models.CharField(blank=True, help_text='Abbreviation of favourite NBA team (e.g. GSW, OKC).', max_length=5, verbose_name='NBA team abbreviation')),
                ('tagline', models.CharField(blank=True, help_text="Short public-facing quote for the bot's profile page.", max_length=200, verbose_name='tagline')),
                ('portrait_url', models.URLField(blank=True, help_text="URL to a custom portrait image for the bot's profile page.", verbose_name='portrait URL')),
            ],
            options={
                'verbose_name': 'bot profile',
                'verbose_name_plural': 'bot profiles',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('windows', models.JSONField(help_text='JSON list of activity windows defining schedule and probabilities.', verbose_name='activity windows')),
                ('active_from', models.DateField(blank=True, help_text='Optional start date. Template is inactive before this date.', null=True, verbose_name='active from')),
                ('active_to', models.DateField(blank=True, help_text='Optional end date. Template is inactive after this date.', null=True, verbose_name='active to')),
            ],
            options={
                'verbose_name': 'schedule template',
                'verbose_name_plural': 'schedule templates',
                'abstract': False,
            },
        ),
    ]
