# Generated by Django 5.2.12 on 2026-03-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global_bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_bot': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile', to=settings.AUTH_USER_MODEL, verbose_name='bot user'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='schedule_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='global_bots.scheduletemplate', verbose_name='schedule template'),
        ),
    ]
