# Generated by Django 5.2.12 on 2026-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='portrait_url',
            field=models.URLField(blank=True, help_text="URL to a custom portrait image for the bot's profile page.", verbose_name='portrait URL'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='tagline',
            field=models.CharField(blank=True, help_text="Short public-facing quote for the bot's profile page.", max_length=200, verbose_name='tagline'),
        ),
    ]
