# Generated by Django 5.2.12 on 2026-03-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_bots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='nfl_team_abbr',
            field=models.CharField(blank=True, help_text='Abbreviation of favourite NFL team (e.g. KC, BUF).', max_length=5, verbose_name='NFL team abbreviation'),
        ),
    ]
