# Generated by Django 5.2.12 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_bots", "0003_add_nfl_team_abbr"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="active_in_worldcup",
            field=models.BooleanField(
                default=False, verbose_name="active in World Cup"
            ),
        ),
    ]
