# Generated by Django 5.2.13 on 2026-04-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_bots', '0005_botprofile_worldcup_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='active_in_ucl',
            field=models.BooleanField(default=False, verbose_name='active in UCL'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='ucl_team_tla',
            field=models.CharField(blank=True, help_text='Abbreviation of favourite UCL team (e.g. LIV, BAR, BAY).', max_length=5, verbose_name='UCL team TLA'),
        ),
    ]
