# Generated by Django 5.2.13 on 2026-04-10 03:35

import django.db.models.deletion
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_bots', '0006_botprofile_active_in_ucl_botprofile_ucl_team_tla'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotArchiveEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('entry_type', models.CharField(choices=[('life_update', 'Life Update'), ('award', 'Award'), ('challenge', 'Challenge'), ('betting_highlight', 'Betting Highlight'), ('social', 'Social')], max_length=20, verbose_name='entry type')),
                ('summary', models.TextField(help_text='1-3 sentence distillation for prompt injection.', verbose_name='summary')),
                ('raw_source', models.TextField(blank=True, help_text='Original text that spawned this entry (e.g. Claude response).', verbose_name='raw source')),
                ('league', models.CharField(blank=True, help_text='Which league context, if any (epl, nba, nfl, ucl, worldcup).', max_length=20, verbose_name='league')),
                ('bot_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_entries', to='global_bots.botprofile', verbose_name='bot profile')),
                ('related_bot', models.ForeignKey(blank=True, help_text='Another bot involved in this entry (for social entries).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in', to='global_bots.botprofile', verbose_name='related bot')),
            ],
            options={
                'verbose_name': 'bot archive entry',
                'verbose_name_plural': 'bot archive entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bot_profile', '-created_at'], name='global_bots_bot_pro_c690ce_idx'), models.Index(fields=['entry_type'], name='global_bots_entry_t_def6f4_idx')],
            },
        ),
    ]
