# Generated by Django 5.2.12 on 2026-03-28 19:30

import django.db.models.functions.text
import django.utils.timezone
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollars ($)'), ('GBP', 'UK Pounds (£)'), ('EUR', 'Euros (€)')], default='USD', max_length=3)),
                ('is_bot', models.BooleanField(default=False, help_text='Designates bot/automated accounts.')),
                ('avatar_icon', models.CharField(default='user-circle', max_length=50)),
                ('avatar_bg', models.CharField(default='#374151', max_length=7)),
                ('avatar_frame', models.CharField(blank=True, default='', max_length=50)),
                ('avatar_crest_url', models.URLField(blank=True, default='')),
                ('profile_image', models.ImageField(blank=True, default='', help_text='Profile photo. Used as avatar when set.', upload_to='profile_images/')),
                ('show_activity_toasts', models.BooleanField(default=True, help_text='Show live activity feed toasts on every page.')),
                ('promo_code', models.CharField(blank=True, default='', max_length=100)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, max_length=8, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), condition=models.Q(('display_name__isnull', False), models.Q(('display_name', ''), _negated=True)), name='users_user_display_name_unique_non_empty_ci')],
            },
        ),
    ]
