# Generated by Django 5.2.12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.OneToOneField(
                blank=True,
                help_text="The real user who created this bot account.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
