# Generated by Django 5.2.12 on 2026-03-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='', help_text='Profile photo. Used as avatar when set.', upload_to='profile_images/'),
        ),
    ]
