# Generated by Django 5.2.12 on 2026-04-06 14:44

import django.db.models.deletion
import vinosports.core.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0005_update_featured_parlay_default_stake_10k'),
        ('worldcup_matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='payout')),
                ('selection', models.CharField(choices=[('HOME_WIN', 'Home Win'), ('DRAW', 'Draw'), ('AWAY_WIN', 'Away Win')], max_length=10, verbose_name='selection')),
                ('odds_at_placement', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='odds at placement')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='worldcup_matches.match', verbose_name='match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_bets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuturesMarket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('season', models.CharField(max_length=10, verbose_name='season')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SUSPENDED', 'Suspended'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10, verbose_name='status')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='settled at')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('market_type', models.CharField(choices=[('WINNER', 'Tournament Winner'), ('FINALIST', 'Finalist'), ('GROUP_WINNER', 'Group Winner')], max_length=15, verbose_name='market type')),
                ('group', models.ForeignKey(blank=True, help_text='Set for GROUP_WINNER markets only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='futures_markets', to='worldcup_matches.group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'futures market',
                'verbose_name_plural': 'futures markets',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('season', 'market_type', 'group')},
            },
        ),
        migrations.CreateModel(
            name='FuturesOutcome',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_winner', models.BooleanField(default=False, verbose_name='is winner')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate if team is eliminated', verbose_name='is active')),
                ('odds', models.DecimalField(decimal_places=2, help_text='Decimal odds (e.g., 2.50)', max_digits=8, verbose_name='odds')),
                ('odds_updated_at', models.DateTimeField(auto_now=True, verbose_name='odds updated at')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='worldcup_betting.futuresmarket', verbose_name='market')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures_outcomes', to='worldcup_matches.team', verbose_name='team')),
            ],
            options={
                'ordering': ['odds'],
                'abstract': False,
                'unique_together': {('market', 'team')},
            },
        ),
        migrations.CreateModel(
            name='FuturesBet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='payout')),
                ('odds_at_placement', models.DecimalField(decimal_places=2, help_text='Decimal odds locked at bet placement', max_digits=8, verbose_name='odds at placement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_futures_bets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='worldcup_betting.futuresoutcome', verbose_name='outcome')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parlay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='payout')),
                ('max_payout', models.DecimalField(decimal_places=2, default=Decimal('10000000000.00'), max_digits=14, verbose_name='max payout')),
                ('combined_odds', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='combined odds')),
                ('featured_parlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_placed_parlays', to='betting.featuredparlay', verbose_name='featured parlay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_parlays', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParlayLeg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('selection', models.CharField(choices=[('HOME_WIN', 'Home Win'), ('DRAW', 'Draw'), ('AWAY_WIN', 'Away Win')], max_length=10, verbose_name='selection')),
                ('odds_at_placement', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='odds at placement')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlay_legs', to='worldcup_matches.match', verbose_name='match')),
                ('parlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='worldcup_betting.parlay', verbose_name='parlay')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'unique_together': {('parlay', 'match')},
            },
        ),
    ]
