# Generated by Django 5.2.12 on 2026-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.PositiveIntegerField(default=100, help_text='Maximum number of registered users. Set to 0 for unlimited.')),
                ('registration_closed_message', models.CharField(default="We've hit our user cap for now. Check back later or follow us for updates on when spots open up.", help_text='Message shown on the signup page when registration is closed.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
