# Generated by Django 5.2.12 on 2026-03-22 16:56

import django.db.models.deletion
import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True, verbose_name='external ID')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='home score')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='away score')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('TIMED', 'Timed'), ('IN_PLAY', 'In Play'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='status')),
                ('matchday', models.IntegerField(verbose_name='matchday')),
                ('kickoff', models.DateTimeField(verbose_name='kickoff')),
                ('season', models.CharField(help_text='e.g. 2025', max_length=10, verbose_name='season')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True, verbose_name='external ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='short name')),
                ('tla', models.CharField(blank=True, max_length=3, verbose_name='TLA')),
                ('crest_url', models.URLField(blank=True, verbose_name='crest URL')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='venue')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MatchNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('body', models.TextField(blank=True, help_text='Free-form match observations for bot context', verbose_name='notes')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name': 'match notes',
                'verbose_name_plural': 'match notes',
            },
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2h_json', models.JSONField(default=list, verbose_name='H2H matches')),
                ('h2h_summary_json', models.JSONField(default=dict, verbose_name='H2H summary')),
                ('home_form_json', models.JSONField(default=list, verbose_name='home team form')),
                ('away_form_json', models.JSONField(default=list, verbose_name='away team form')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='fetched at')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last attempt at')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hype_stats', to='matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name': 'match stats',
                'verbose_name_plural': 'match stats',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team', verbose_name='away team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team', verbose_name='home team'),
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bookmaker', models.CharField(max_length=100, verbose_name='bookmaker')),
                ('home_win', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='home win')),
                ('draw', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='draw')),
                ('away_win', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='away win')),
                ('fetched_at', models.DateTimeField(verbose_name='fetched at')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name_plural': 'odds',
                'ordering': ['-fetched_at'],
                'unique_together': {('match', 'bookmaker')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('season', models.CharField(max_length=10, verbose_name='season')),
                ('position', models.IntegerField(verbose_name='position')),
                ('played', models.IntegerField(default=0, verbose_name='played')),
                ('won', models.IntegerField(default=0, verbose_name='won')),
                ('drawn', models.IntegerField(default=0, verbose_name='drawn')),
                ('lost', models.IntegerField(default=0, verbose_name='lost')),
                ('goals_for', models.IntegerField(default=0, verbose_name='goals for')),
                ('goals_against', models.IntegerField(default=0, verbose_name='goals against')),
                ('goal_difference', models.IntegerField(default=0, verbose_name='goal difference')),
                ('points', models.IntegerField(default=0, verbose_name='points')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.team', verbose_name='team')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('team', 'season')},
            },
        ),
    ]
