# Generated by Django 5.2.12 on 2026-04-04 20:07

import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalKnowledge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('headline', models.CharField(help_text="Short headline (e.g. 'Messi rejoins Barcelona for a farewell tour')", max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Optional expanded context — only include if bots need more than the headline')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first. Keep 3-5 active at a time.')),
            ],
            options={
                'verbose_name': 'Global Knowledge',
                'verbose_name_plural': 'Global Knowledge',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
