# Generated by Django 5.2.12 on 2026-03-28 19:30

import vinosports.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=vinosports.core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('trigger_type', models.CharField(choices=[('PRE_MATCH', 'Pre-match hype'), ('POST_BET', 'Post-bet reaction'), ('POST_MATCH', 'Post-match reaction'), ('REPLY', 'Reply to comment')], max_length=20, verbose_name='trigger type')),
                ('prompt_used', models.TextField(blank=True, verbose_name='prompt used')),
                ('raw_response', models.TextField(blank=True, verbose_name='raw response')),
                ('filtered', models.BooleanField(default=False, help_text='True if the post-hoc filter rejected this comment.', verbose_name='filtered out')),
                ('error', models.TextField(blank=True, verbose_name='error')),
            ],
            options={
                'verbose_name': 'bot comment',
                'verbose_name_plural': 'bot comments',
                'abstract': False,
            },
        ),
    ]
