# Generated by Django 5.2.12 on 2026-03-28 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nba_bots', '0001_initial'),
        ('nba_discussions', '0001_initial'),
        ('nba_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcomment',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_comment_meta', to='nba_discussions.comment', verbose_name='posted comment'),
        ),
        migrations.AddField(
            model_name='botcomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_comments', to='nba_games.game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='botcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_replies', to='nba_discussions.comment', verbose_name='replied to'),
        ),
    ]
