# Generated by Django 5.2.12 on 2026-03-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epl_bots', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botcomment',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_bot': True}, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_bot_comments', to=settings.AUTH_USER_MODEL, verbose_name='bot user'),
        ),
        migrations.AddIndex(
            model_name='botcomment',
            index=models.Index(fields=['match', 'trigger_type'], name='epl_bots_bo_match_i_ebde4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='botcomment',
            constraint=models.UniqueConstraint(fields=('user', 'match', 'trigger_type'), name='unique_epl_bot_comment_per_trigger'),
        ),
    ]
